In [2]:
#Pytorch Intro:
#GPU acceleration: makes code run faster
import torch
torch.__version__ #used to find the version of the torch your are youring
#tensor shape of [3,224,224] is a 3 dimensional tensor to represent images where the dimensions are [color_channels,height,width]
#what is a tensor:
#area vector: the cross product of the sides, which means that the resulting vector is proportiional to teh area of the vecor and
#perpendicular to the surface
#vectors are subsets of a tensor class, for which you must understand vector components and basis vectors
# the cartesian plane has 3 coordinate basis vectors orthogonal to eachother whose linear combination spans the vector space
# these basis vectors have length of one, i hat j hat and k hat all in increasing x,y, and z directions respectively
# to find x and y components, just project the vector onto the axis
# an n-dim vector can be expressed as a sum of n orthogonal basis vectors  
# so vector A = Ax * xhat + Ay * yhat + Az * zhat
#where Ax Ay Az are components of a in each direction

#here, we need only one index for each of these: A[0], A[1], A[2] because there is only one basis vector per component
#making a vector a rank 1 tensor
#scalars are rank 0 since they have no directional indicator per component


#2D tensor:
# Axx Axy Axz
# Ayx Ayy Ayz
# Azx Azy Azz
# xy, as a cross product cannot be expressed as a linear combination of x and y, so they are an entirely different basis vector
# Exe: lets suppose you have a 3-D object with axis in the x, y, and z direction. Then, forces can be applied on any of the 3 direction
#themselves in different directions. eg in the x direction there are forces in the x,y,and z direction. Thus, you must express the 
#problem as a 2D tensor as shown above, where you need 2 indexes to access all elements.
#NOTE: this is just an interpretation, in reality tensors are more abstract and can represent many different things



'2.5.1'

In [18]:
#creating a 0-dim tensor (scalar)
scalar = torch.tensor(data=7) #this way, you can enter in an exact value for the tensor in the parenthesis
print(f"Tensor: {scalar} \n ndim: {scalar.ndim} \n item {scalar.item()}") #this just displays it, but only when it is the last line
scalar.ndim #check the dimensions of the tensor object

scalar.item() #turns the 0dim tensor into a python integer


Tensor: 7 
 ndim: 0 
 item 7


7

In [20]:
#now vectors:
#RANK/ORDER: rank is essentially the number of indicies needed to access every element in the tensor
#DIMENSIONS: size of the underlying vector space of each index

#EXE: a rank 1 tensor in 3 dimensions is like [4,1,6], because it used one index so rank 1, and has 3 values, so the vector
#lies in R3 or 3 dimensions



vector = torch.tensor(data=[3,2]) #creates a rank 1 tensor with 2 Dimensions
vector.ndim #CONFUSING: ndim will return the rank, while shape will return the shape
vector.shape #this will return a torch.Size object of [2], which means there are two elements in the first dimension


torch.Size([2])

In [5]:
#now matrix

MATRIX = torch.tensor([[1,2],[3,4]]) #creates a matrix, which has 2 dimensions and size [2,2]
MATRIX.ndim # returns 2
MATRIX.shape # returns [2,2]

torch.Size([2, 2])

In [6]:
#tensors!

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR.ndim #returns 3
TENSOR.shape #returns [1,3,3]

#NOTE: vectors and scalars use lowercase letters like y or a, and matricies and tensors use uppercase like W or X

torch.Size([1, 3, 3])

In [7]:
#usually, machine learning starts with large random tensors which are adjusted as it works through the data
# process: start with rand numbers > look at data > update rand nums > look at data > update rand ...
# Start with random: initialization
# Looks at data: representation
# Updates random numbers: optimization


#for random numbers, use torch.rand(), and pass in a size parameter

random_tensor = torch.rand(size=(3,2)) # creates a random tensor of size [3,2], meaning a matrix 

random_tensor,random_tensor.dtype #this is hwo you print both, and dtype to find the type of data, usually float 32
#NOTE: this will output as a tuple!

(tensor([[0.9094, 0.9527],
         [0.0982, 0.1147],
         [0.8619, 0.6329]]),
 torch.float32)

In [8]:
#fill a tensor with 0s and ones: use zeros command
#NOTE: here, you pass in a parameter with parenthesis like this
zero_tensor = torch.zeros(size=(3,2))
zero_tensor,zero_tensor.dtype

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 torch.float32)

In [9]:
#same thing for ones
ones = torch.ones(size=(3,2))
ones, ones.dtype, ones.ndim, ones.shape

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 torch.float32,
 2,
 torch.Size([3, 2]))

In [10]:
#arange of tensor values
#use torch.arange(start, end, step), zero included, 10 not
#RETURNS A TENSOR
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#if you want a zeros or a ones tensor that has the same shape as an existing tensor, use
#zeros_like and ones_like, and then imput a torch.tensor object as the param

ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
#tensor datatypes:
#different types of tensors optimized for GPU and CPU, which are different
# default is torch.float32 or torch.float, which is 32 bit floating point number

#torch.float16 or torch.half, and torch.float64 or torch.double are other ones
#also 8, 16, 32, and 64 bit integers

#more bits > more precision > higher accuracy > more compute

float_32_tensor = torch.tensor([1,2,3,4], dtype=torch.float32, device=None, requires_grad=False)
float_32_tensor.dtype
#where dtype is the type of tensor
#device defaults to None, which used default tensor type (CPU)
#requires_grad if true will record operations done on the tensor




torch.float32

In [21]:
# getting attributes from tensors: shape, dtype, and device

random_tensor = torch.rand(size=(3,2))
print(f"The generated tensor is: {random_tensor}")
print(f"Shape of tensor is: {random_tensor.shape}")
print(f"Datatype of tensor is: {random_tensor.dtype}")
print(f"Device of tensor is: {random_tensor.device}")



The generated tensor is: tensor([[0.9600, 0.4487],
        [0.0355, 0.2010],
        [0.5507, 0.2576]])
Shape of tensor is: torch.Size([3, 2])
Datatype of tensor is: torch.float32
Device of tensor is: cpu


In [ ]:
#tensor manipulations
#adding, substracting, element-wise multiplication, division, matrix multiplication

#adding:
TENSOR = torch.tensor([1,2,3], dtype=torch.float32, device=None, requires_grad=False)
TENSOR = TENSOR + 10 # returns [11,12,13]
TENSOR = TENSOR - 10 # returns [1,2,3]
TENSOR = TENSOR * 10 #returns 10,20,30
TENSOR * 10 # returns 100,200, 300, BUT DOES NOT MODIFY THE NUMBERS INSIDE THE TENSOR!!

#can also use torch.mul or torch.add to preform these operations: torch.add(tensor,10) or torch.mul(tensor,10) but less common for
#basic operations

tensor = torch.tensor([1,2,3])
torch.mul(tensor,tensor) #returns 1,4,9, HERE: each element multiplies its equivalent, so index 0 with index 0, index 1 with 1...
#can mutliply any tensors as long as their shapes are broadcastable
#Broadcasting: pytorch and numpy can stretch certain vectors across certain dimensions without copying data 
#WORKS WHEN THE DIMENSIONS ARE EQUAL OR ONE OF THEM IS OF DIM 1
# pytorch prepends 1s to the shape of the smaller dim tensor untill they align

#exe: multiply a shape A=(2,3) with a B(3)
#first, prepend 1 so that (3) becomes (1,3)
#then, compare dims:
# 2 vs 1, so expand B from (1,3) to (2,3) by copying the number
# 3 vs 3, match so works

#exe A=[[[1,2],[3,4]]] has shape 1,2,2 and B= [1,2] has shape [2]
# B goes to 1,1,2 and so all dimensions are compatible
# B becomes [[[1,2],[1,2]]] and then element multiply






tensor([1, 4, 9])

In [15]:
# now matrix multiplication:
#using torch.matmul()
# here, inner dims must match, resulting shape has outer dims

#Transpose:
#can use torch.transpose(imput,dim0,dim1) where imput is the tensor to operate on, and dim0 and dim1 are the dimensions to be swapped
# can also use tensor.T where tensor is the tensor to be transposed
# where if size is (5,10,11), the 5 is the 0th dimension, the 10 is the num elements in teh 1st dimension, and the 11 is in the 2nd dim
#

A = torch.rand(3,2)




#NOTE: UNDERSTAND THE MATH BEHIND TENSOR DOT PRODUCT, TENSOR MATRIX MULTIPLICATION, AND TENSOR TRANSPOSE

#Now, normally matrix multiplicaion does not work for non-matricies, but torch.matmul() makes it work using special rules:
#NOTE: PROCESS CALLED BATCH MATRIX MULTIPLICATION
# A = torch.rand(10,3,2)
# B = torch.rand(10,2,3)
#pytorch treats this at having to solve 10 matrix multiplications on teh (3,2) with (2,3) matrix, where the multiplications are 
#done between the matricies of corresponding indicies in the 10, aka torch.matmul(A[0],B[0]), then torch.matmul(A[1],B[1])
# and the result will be in the form of shape = (10,3,3)

#matrix mutliplication is conducted using broadcasting rules, meaning (10,2,3) can be multiplied by (1,3,2)
# and (10,2,3) can be multiplied by (1,1,3) by broadcasting or transposing and broadcasting (IDK WHICH TO GO FOR)

#same for (10,10,3,2) matmul (10,10,2,2), you are doing batched matrix multiplication on the batched dimensions, and then normal
#matmul on the other ones

#DOT PRODUCT:
#NICKNAME FOR MATRIX MULTIPLICATION, NOT THE ELEMENT-WISE MULTIPLICATION

#TRANSPOSE
# .T is for 2d matricies only, transpose is for swapping 2 dimensions only,and permute(neworder=(2,0,1)) is for swapping everything
# remember, a transpose doesnt actually change the tensor, just the way its strides are interpreted
#exe: for [[[1,2],[3,4]],[[5,6],[7,8]]] , which is size 2,2,2
#this tensor has 2 slices, or elements in its outer dimension
# each slice has 2


#what it does it that it maps the coordinates of each point in the tensor to its transposed location
# lets suppose that there is element b located at A[1][3][4], where 1 is the num elements in the 1st dimension, 3 is num in second
#dimension, and 4 is elements in 3rd dimension, if you do torch.transpose(tensor,1,0) it will swap the 1 and 0 dimensions, which'
#means is will swap 1 and 3

#thus, the new location of b, which was A[1][3][4] is now A[3][1][4], and the same will happen for all other elements in the tensor


NameError: name 'B' is not defined

In [ ]:
#Linear Layer
# Formual for a linear layer: y = xW^T +b
#where X is the imput to the layer, usually of size (batch_size, in_features)
# W or A is the weights matrix, initially randomized of size (out_features, in_features)
# T is to transpose it
# b is the bias, of size (out_features) (will be broadcast to (batch_size, out_features) when adding)
# y is the output, of size (batch_size, out_features), a manipulation of the imput in hopes to discover a pattern in it

torch.manual_seed(42) #set a manual seed so that the randomization of the weights is consistant
linear = torch.nn.Linear(in_features=2,out_features=6)
x = torch.rand(3,2)
print(f"Input is {x} with dimensions {x.shape}")
result = linear(x)
print(f"Output is {result} with dimensions {result.shape}")


# the weights array is size (out_features, in_features), meaning it has out_features arrays of in_feature elements.
# each row in this matrix is the weight vector for one neuron (so if a linear layer has 6 out_features it has 6 neurons)
# so if a lin layer has 3 in_features and 6 out features, it will have 6 neurons each with a weights vector of size 3

# the weights array for each neuron is of size 3 because it will recieve imput from 3 neurons in the form of an array
# that is itself size 3
# this way, it is multiplying a size 3 array by anouther size 3 array transposed, resulting in a scalar plus bias in a 
#normalizing function.



#DRAW A DIAGRAM IT MAKES SENSE!! 




Input is tensor([[0.2666, 0.6274],
        [0.2696, 0.4414],
        [0.2969, 0.8317]]) with dimensions torch.Size([3, 2])
Output is tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddmmBackward0>) with dimensions torch.Size([3, 6])


In [ ]:
#Now, we move on to aggregation techniques, or how to make a tensor go from many values to fewer (INCLUDES TYPE CHANGES)

x = torch.arange(0,100,10)

print(f"Maximum value = {x.min()}")
print(f"Maximum value = {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") #MUST BE A FLOAT TO FIND THE MEAN, SO TYPECAST
print(f"Sum: {x.sum()}")

#CAN DO THE SAME WITH TORCH METODS LIKE torch.max or torch.min

#POSITIONAL MIN/MAX

#use torch.argmax() or torch.argmin() to find the index of where the max or min is, or tensor.argmax() and tensor.argmin()

print(f"The max is at index {torch.argmax(x)}")




Maximum value = 0
Maximum value = 90
Mean: 45.0
Sum: 450
The max is at index 9


In [ ]:
#NOTE, the only methods that actually modify the origional tensor are the inplace methods ending in _, the rest return a new one
#reshapes, stacking, squeezing, and stretching

tensor = torch.rand(size=(3,2))
print(tensor)

new = torch.reshape(input=tensor,shape=(1,3,2)) #reshapes as in broadcasts only with valid broadcasts 
#RESHAPE COPIES THE DATA AND RETURNS A NEW TENSOR WITH THAT DATA IN IT
#NOTE: DOES NOT MODIFY THE ORIGIONAL TENSOR

new.view(size=(3,2)) # here, you can view a tensor as a new size without changing it
#NOTE: all this does is return a new tensor with the same memory data (meaning editing the view edits the tensor)
#DOES NOT COPY DATA





tensor2 = torch.rand(size=(3,2))
print(tensor2)

concat = torch.stack((tensor,tensor2),dim=1) # adds a new dimension at dim 0 (the furthest)
print(concat)
# exe: t1 = [1,2], t2 = [3,4], t3 = [5,6]
# each of these tensors have shape [2]
# thus, when you add them with dim=0, the resulting shape will be of size [3,2], since 3 is at position of dim 0
# if you were to add at dim 1, the resulting shape is [2,3]. REMEMBER: TENSORS ARE ABSTRACT, SO THE WAY THIS WORKS IS LIKE THIS:
# t1 = [a,b] where a is an index 0 in dim 0, and b is an index 1 in dim 0
# when you stack it, you stack on dim 1, so a now is 

#NOTE:
#Mental Trick: try to think of each dimension as a label, like (2,3,2) could be (channels, width, height)
# a permutation just changes the way the data is ordered, like first its the set of all channels, so 3 objects, then all widths,
# then all heights
# so if you have a tensor to store image data (channels, height, width) of size (3,255,255), and you permute it to 
# (height, channels, width) its just first a set of all the heights to index, then channels with 3 objects, then widths.
# same thing for stacking, which really is just creating a dimension. When you have two objects of size [2] can you stack them on
# the first dimension, you create a tensor of class [2,2], where  first you index by the first index in the tensor, and the 
# by which tensor it is, so T[0][0] means let me get the 0th index of the first tensor



#NOW, FOR squeeze, unsqueeze and permute
#this will make the tensor of size [2], removing all one element dimensions (rank 1 size [2])
testor = torch.rand(size=(1,2,1))
t2 = torch.squeeze(testor)

#this will add a dimension where you want it to be of size 1, in accordance with broadcasting rules
t2 = torch.unsqueeze(input=testor,dim=3)
t2.shape # shape is now 1,2,1,1

#permute is just like a transpose, but for all dimensions of the tensor
t2 = torch.permute(input=testor,dims=(1,0,2))
t2.shape






tensor([[0.0931, 0.9193],
        [0.2999, 0.6325],
        [0.3265, 0.5406]])
tensor([[0.9662, 0.7304],
        [0.0667, 0.6985],
        [0.9746, 0.6315]])
tensor([[[0.0931, 0.9193],
         [0.9662, 0.7304]],

        [[0.2999, 0.6325],
         [0.0667, 0.6985]],

        [[0.3265, 0.5406],
         [0.9746, 0.6315]]])


torch.Size([2, 1, 1])

In [ ]:
#indexing tensors

#NOTE: SUPER IMPORTANT!!! reshape and broadcast are not the same things! reshape only cares that the number of elements stays the
#same. for view, it must have the same number of sides, but also must be contiguous in memory. THus, you will need to call 
#tensor.contiguous for it to work. NOW, reshape will attempt to call view, but will end up copying the memory if the data is not
#contiguous in memory, so its like a more advanced copy


#MECHANICS OF TENSORS DEEP DOWN:
# if you write x = torch.rand(size=(8,15,17))
# while the object x is a tensor, the memory is stored just as a contiguous array of size 8*15*17 elements
# thats 2040 elements layed out in row-major style (c-style)
# Row major order just means that rows are placed after eachother 
# so x[i][j][k] is matter to memory index i*(15*17) + j*(17) + k
# pytorch tensors contain metadata with shape (8,15,17) and strides (255,17,1) wich is how much to offset by each index ijk
# a tensor reshape or view is just a change to the shape and stride math of the object. The memory remains unchanged
#PROVE IT ON PAPER

# to store tensor shape (2,2,3), the last dimension (index 2 here) changes the fastest, so it is [0][0][0], [0][0][1], ..
# the strides are (6,3,1). 


#transposes and reshapes are different, with transposes usually making the data non contiguous because the memory layout
#no longer matches the row-major order of the new shape
# Transpose is the more mathematical one, with the axis actually swapping, reshape is just a way of visualizing the data differently


# BASICALLY, if you have an origional tensor x of size (3,6,8) and you say a = x.reshape(8,6,3),
# and b = x.permute(2,1,0), the results will be different even if they have the same size

#THAT BEING SAID, PERMUTE DOES NOT NECESSARILY HAVE TO CHANGE THE MEMORY, IT CAN STILL GET BY ON JUST CHANGING THE STRIDE
# AND SHAPE. SUPER IMPORTANT: CONTIGUOUS DOES NOT MEAN THAT THERE ARE BREAKS IN THE MEMORY, IT JUST MEANS THAT FOR A TENSOR
# THAT IS IT STORED IN THE ROW MAJOR ORDER IMPLIED BY ITS SHAPE AND STRIDE. IN OTHER WORDS, IF YOU LOOP THROUGH
#ALL THE ELEMENTS IN THE SHAPE IN ORDER, WITH THE LAST DIMENSION CHANGING THE FASTEST, THE PIECES SHOULD REMAIN IN ORDER
# AND YOU SHOULDN't BE JUMPING AROUND, WHICH OF COURSE ISN'T TRUE FOR A TRANSPOSE

# THUS, RESHAPE WILL RETURN A VIEW IF THE TENSOR IS STILL CONTIGUOUS, BUT IF NOT WILL HAVE TO COPY AND MAKE IT CONTIGUOUS

#NOTE:
#WHY DOES BEING CONTIGUOUS MATTER?
#to reshape without copying, pytorch must be able to simply re-interpret the data, which is only possible when it is in row
#major order!! REASON BEING, if you have a tensor of size (3,4) and reshape it to be size (2,6), the 7th element of the 
#first tensor is the seventh element of the second tensor. The only thing that changed is how you group it

#DURING A TRANSPOSE HOWEVER, the data is no longer contiguous, so the seventh element of the origional tensor is not
#the seventh of the final tensor, so 




x = torch.arange(start=1,end=10,step=1)
x = x.reshape(shape=(3,1,3))
x,x.shape


#now for the actual indexing:

print(f"The first bracket is the outer dimension (dim 0): {x[0]}")
print(f"the second bracket is the middle dimension (dim 1): {x[0][0]}")
print(f"The last bracket is the outer dimension (dim 2): {x[0][0][0]}")


The first bracket is the outer dimension (dim 0): tensor([[1, 2, 3]])
the second bracket is the middle dimension (dim 1): tensor([1, 2, 3])
The last bracket is the outer dimension (dim 2): 1


In [ ]:
#QUESTION: if you apply a reshape on a transposed tensor, does the tensor need to change the way it is?

tensor1 = torch.arange(start=1,end=13,step=1)
tensor2 = tensor1.reshape(shape=(3,4))
print(tensor2,tensor2.shape)
tensor3 = tensor2.transpose(0,1)
print(tensor3,tensor3.shape)
tensor4 = tensor3.reshape(shape=(3,4))
print(tensor4, tensor4.shape)  #so after transposing and then resizing to the origional and then indexing it is not the same

#WHY DOES IT MATTER?:
# given tensor [[1,2,3,4],[5,6,7,8],[8,10,11,12]]
# here, the memory is contiguous 1...12
# if you transpose it, it will become [[1,5,9],[2,6,10],[3,7,11],[4,8,12]]
# but the memory is still 1...12 but now non-contiguous
# now, if you do a reshape now, lets say to (4,3), it will want to turn the tensor into [[1,5,9,2],[6,10,3,7],[11,4,8,12]]
# But that is not possible by only changing shape and stride since the memory is still 1...12
# Thus, you have to copy the memory and make it contiguous, and then you can do the shape and stride trick
# since if you just change the shape to (4,3) and the stride to (3,1), the resulting reshape will return
# [[1,2,3],[4,5,6],[7,8,9],[10,11,12]], which is not what you want


#now check:
print(f"The 7th element of tensor 2 is {tensor2[1][3]}")
print(f"The 7th element of tensor 3 is {tensor2[2][1]}")
#notice they are not the same, so the order is fundamentally differnt

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) torch.Size([3, 4])
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]) torch.Size([4, 3])
tensor([[ 1,  5,  9,  2],
        [ 6, 10,  3,  7],
        [11,  4,  8, 12]]) torch.Size([3, 4])
The 7th element of tensor 2 is 8
The 7th element of tensor 3 is 10


In [ ]:
#Indexing but actually

tensor = torch.arange(start=1,end=10,step=1).reshape(shape=(3,3))
#you can also use :'s to mean all columns at that level, so [:,0] means all elements in the first dim with second dim index 0
print(f"The tensor as a whole is: \n{tensor}")
print(f"Basically, [:,0] returns: \n{tensor[:,0]} ")


The tensor as a whole is: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Basically, [:,0] returns: 
tensor([1, 4, 7]) 


In [ ]:
#Pytorch and Numpy
#two methods to use are torch.from_numpy(numpy)
# and torch.Tensor.numpy(tensor)

import torch
import numpy as np
array = np.arange(start=1.0,stop=10.0,step=1.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor,tensor.dtype


(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.float32)

In [ ]:
#Randomness

rand_tensor1 = torch.rand(size=(3,4))
rand_tensor2 = torch.rand(size=(3,4))
print(f"{rand_tensor1}\n {rand_tensor2}")
#are they equal anywhere
rand_tensor1 == rand_tensor2 #compares element wise


tensor([[0.5989, 0.1208, 0.0331, 0.5088],
        [0.9559, 0.7885, 0.2089, 0.4351],
        [0.1314, 0.2588, 0.5905, 0.7723]])
 tensor([[0.9142, 0.0409, 0.8343, 0.1474],
        [0.6872, 0.9231, 0.5070, 0.9549],
        [0.0740, 0.3090, 0.7916, 0.3911]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#Now for the Reproducable randomness

import torch
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
rand_tensor1 = torch.rand(size=(3,2))
#NOTE: you gotta reset the seed everytime a new rand is called
torch.manual_seed(seed=RANDOM_SEED)
rand_tensor2 = torch.rand(size=(3,2))
rand_tensor1,rand_tensor2,rand_tensor1 == rand_tensor2



(tensor([[0.8823, 0.9150],
         [0.3829, 0.9593],
         [0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150],
         [0.3829, 0.9593],
         [0.3904, 0.6009]]),
 tensor([[True, True],
         [True, True],
         [True, True]]))

In [ ]:
#TENSORS ON GPUs
#generally nvidia gpus with cuda
#ways to access GPU: google colab, your own, or cloud computing
#to check if you have access to nvidia GPU, run !nvidia-smi ! IS BANG, AND #! IS SHEBANG
!nvidia-smi
# use torch.cuda package for to get torch working
torch.cuda.is_available()

#to make a condition cuda not available to run on cpu

device = "cuda" if torch.cuda.is_available() else "cpu" #best practice to run device agnostic code
device

#to cound the number of gpus you have available
torch.cuda.device_count()


#for running on mac:
torch.backends.mps.is_available() #this is like the torch.cuda.is_available
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

#for the ultimate agnostic case, use an if statment
if torch.cuda.is_available():
    device = "cuda" #uses nvidia drivers if available
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

print(device)
# Make me a tic tac toe solver



#to move tensors from cpu to gpu, use torch.Tensor.to(device)

tensor = torch.tensor([1,2,3])
print(f"current tensor is: {tensor} on device {tensor.device}")
tensor_on_gpu = tensor.to(device)
print(f"new tensor is still {tensor_on_gpu} on device {tensor_on_gpu.device}") #mps:0 means it stores it on the 0th gpu index
#if you have multiple gpus

#moving tensors back to cpu
# if you use the old method of torch.tensor.numpy() it will error because the tensor is not stored in memory
#thus, you must use the torch.tensor.cpu()


#!nvidia-smi
# torch.cuda.is_available
# device = "cuda"
# torch.cuda.device_count()
# for multiple GPUs, use DDP, or distributed data parallel

zsh:1: command not found: nvidia-smi
mps
current tensor is: tensor([1, 2, 3]) on device cpu
new tensor is still tensor([1, 2, 3], device='mps:0') on device mps:0


In [ ]:
#HW:

#random tensor with shape (7,7)

import torch
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
rand_tensor = torch.rand(size=(7,7))
print(rand_tensor)
#torch.manual_seed(seed=RANDOM_SEED)
rand_tensor2 = torch.rand(size=(1,7))
prod_tensor = torch.matmul(rand_tensor,rand_tensor2.transpose(dim0=0,dim1=1))  #.T or .transpose(dim0=0,dim1=1)
print(prod_tensor,prod_tensor.shape)


#NOTE, only reset the random seed if you want the random numbers created to be exactly the same
#usually, just one random seed will suffice since after that all the random numbers generated are reproducible

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [ ]:
#HW cont
#torch.manual_seed(seed= is for CPUs! how to do it for GPUs?)

#set_rng_state_all sets the rng state for all gpus to the same number. can also use torch.cuda.manual_seed_all

RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"
print(device)

torch.manual_seed(seed=RANDOM_SEED)
t1 = torch.rand(size=(2,3))
t2 = torch.rand(size=(2,3))
t1_on_gpu = t1.to(device)
t2_on_gpu = t2.to(device)
device,t1_on_gpu, t2_on_gpu, 

prod = torch.matmul(t1_on_gpu, t2_on_gpu.T)
prod, prod.shape

print(f"Min value is {prod.min()}")
print(f"Max value is {prod.max()}")
print(f"Min value index is {prod.argmin()}")
print(f"Max value index is {prod.argmax()}")



mps
Min value is 0.3647301495075226
Max value is 0.5617256760597229
Min value index is 0
Max value index is 3


In [ ]:
#10
RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(size=(1,1,1,10))
print(f"The origional tensor is {tensor, tensor.shape}")
t_squeeze = tensor.squeeze()
print(f"The squeezed tensor is {t_squeeze,t_squeeze.shape}")
  


The origional tensor is (tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
The squeezed tensor is (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
