In [3]:
#Start of the HW:
#create a random tensor of size (7,7)
import torch

tensor = torch.randn(size=(7,7))
tensor,tensor.shape,tensor.ndim,tensor.dtype,tensor.device

(tensor([[ 0.2228, -1.0622,  0.5825, -1.1417, -0.2941, -0.3334,  0.3948],
         [ 0.1994,  0.6134, -1.4236,  0.6647, -0.1401, -0.7045,  0.9789],
         [-0.7597,  0.1969,  0.0376,  0.6718,  0.1451, -0.4637,  0.2024],
         [-0.3155,  0.5454, -0.6607,  0.3098, -0.8662,  1.2949, -0.7829],
         [ 0.6864, -0.6070,  1.0813,  0.0467, -1.4055,  0.2871, -0.5260],
         [ 0.1096, -0.4650,  1.6443,  0.0326,  1.0101,  1.8002, -0.1567],
         [ 1.3754,  2.2755,  2.0449, -0.4043,  0.1667, -1.0225,  2.8895]]),
 torch.Size([7, 7]),
 2,
 torch.float32,
 device(type='cpu'))

In [7]:
#use the above tensor and multiply by a tensor of size (1,7)
print(f"The first tensor is of size {tensor.shape}")
#thus, have ot multiply by the transpose of a 1,7 tensor
tensor2 = torch.rand(size=(1,7))

MANUAL_SEED = 42
torch.manual_seed(MANUAL_SEED)
resTensor = torch.matmul(tensor,tensor2.T)
resTensor

The first tensor is of size torch.Size([7, 7])


tensor([[-1.8615e+00],
        [ 6.0288e-01],
        [-1.2367e-03],
        [ 5.0402e-01],
        [-2.2082e-03],
        [ 1.7681e+00],
        [ 3.8827e+00]])

In [ ]:
# to set random seed for GPU:
torch.cuda.manual_seed()
torch.cuda.manual_seed_all() #sets the seed for all gpus

In [ ]:
'''
important tensor functions:

torch.tensor()
.to(device)
.reshape()
.view()
.transpose()
.permute()
.squeeze() #adds dimensions to the data
.unsqueeze()
np.arange(start,stop,step)
torch.arange(start,stop,step)
tensor1 == tensor2 will elementwise compare them, returning a tensor of their sizes with true or false.
matmul
mul
.type() to change the type 
torch.from_numpy()







'''
ten1 = torch.randn(size=(3,3))
ten2 = torch.randn(size=(3,3))
print(f"{ten1 == ten2}") #or torch.eq(ten1,ten2)

torch.sum(torch.eq(ten1,ten2))
# for multiclass, use argmax to replace each element with an index and then use the .eq and sum and divide by torch.numel()



tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


tensor(0)

In [15]:
#create two rand tensors of size (2,3) on gpu
torch.manual_seed(1234)
size = (2,3)

#device agnostic code
if torch.cuda.is_available():
    device="cuda"
elif torch.backends.mps.is_available():
    device="mps"
else:
    device="cpu"

tensor1 = torch.randn(size=size).to(device)
tensor2 = torch.randn(size=size).to(device)
tensor1,tensor2



(tensor([[ 0.0461,  0.4024, -1.0115],
         [ 0.2167, -0.6123,  0.5036]], device='mps:0'),
 tensor([[ 0.2310,  0.6931, -0.2669],
         [ 2.1785,  0.1021, -0.2590]], device='mps:0'))

In [17]:
#multiply the two above tensors

tenmul = torch.matmul(tensor1,tensor2.T)
tenmul

tensor([[ 0.5595,  0.4036],
        [-0.5087,  0.2792]], device='mps:0')

In [42]:
#max and min values
max = tenmul.max()
min = tenmul.min()

#argmin returns the index for a list, but argmin in a dimension will go to that dimension and replace it with the index
argmin = torch.argmin(tenmul,dim=0)


#NOTICE: dim=0 means reduce by the 0th dimension: thus, it will compare the slices inside of the 0th dim elementwise to
#find the largest index
#EXE:

tens1 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]).type(torch.float) #2,2,3 shape
tens2 = torch.randint_like(input=ten1,low=0,high=10)
tens1,tens2

print(tens1.shape)
dim0comp = torch.argmax(tens1,dim=0)
print(dim0comp,dim0comp.shape) #this will return a shape 2,3 with element wise compare

dim1comp = torch.argmax(tens1,dim=1) #this is 
print(dim1comp,dim1comp.shape)

dim2comp = torch.argmax(tens1,dim=2) #this is 
print(dim2comp,dim2comp.shape)




torch.Size([2, 2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]]) torch.Size([2, 3])
tensor([[1, 1, 1],
        [1, 1, 1]]) torch.Size([2, 3])
tensor([[2, 2],
        [2, 2]]) torch.Size([2, 2])


In [48]:
#max and min values
max = tenmul.max()
min = tenmul.min()
print(tenmul,max,min)

argmax = torch.argmax(tenmul)
print(f"\n{argmax}")


tensor([[ 0.5595,  0.4036],
        [-0.5087,  0.2792]], device='mps:0') tensor(0.5595, device='mps:0') tensor(-0.5087, device='mps:0')

0
